[package]
org = "org269"
name = "tldr_api"
version = "0.1.0"
distribution = "2201.8.5"

[build-options]
observabilityIncluded = true

[dependencies]
"ballerinax/postgresql.driver" = "1.5.0"
"ballerinax/postgresql" = "1.11.0"
